# Generated by Django 3.0.4 on 2020-03-28 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_organization_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='call_sid',
            new_name='sid',
        ),
        migrations.AddField(
            model_name='response',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
