# Generated by Django 3.0.4 on 2020-04-11 20:43

import asfour.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_auto_20200409_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='method',
            field=models.CharField(choices=[('sms', 'SMS'), ('voice', 'Voice'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='sms', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='recording',
            field=models.FileField(blank=True, null=True, storage=asfour.storage_backends.PrivateMediaStorage(), upload_to='files/'),
        ),
        migrations.AddField(
            model_name='response',
            name='method',
            field=models.CharField(choices=[('sms', 'SMS'), ('voice', 'Voice'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='sms', max_length=50),
        ),
    ]
