# Generated by Django 3.0.4 on 2020-04-11 21:02

import asfour.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_auto_20200411_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recording',
            field=models.FileField(blank=True, null=True, storage=asfour.storage_backends.PublicMediaStorage(), upload_to='files/'),
        ),
    ]
