# Generated by Django 3.0.4 on 2020-04-12 20:02

import asfour.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_auto_20200411_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recording',
            field=models.FileField(blank=True, null=True, storage=asfour.storage_backends.PrivateMediaStorage(), upload_to='files/'),
        ),
    ]
