# Generated by Django 3.0.4 on 2020-04-12 21:25

import asfour.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_auto_20200412_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recording',
            field=models.FileField(blank=True, null=True, storage=asfour.storage_backends.PublicMediaStorage(), upload_to='files/'),
        ),
    ]
