# Generated by Django 3.0.4 on 2020-04-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_auto_20200413_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='method',
            field=models.CharField(choices=[('sms', 'SMS'), ('voice', 'Voice'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('mixed', 'Mixed')], default='sms', max_length=50),
        ),
    ]
