# Generated by Django 3.0.4 on 2020-05-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0017_auto_20200522_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ('-date_received',)},
        ),
        migrations.AddField(
            model_name='messagelog',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=40),
        ),
    ]
