# Generated by Django 3.0.8 on 2020-08-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0018_auto_20200527_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='async_task_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
