# Generated by Django 3.1.7 on 2021-03-12 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0019_auto_20200814_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
