# Generated by Django 3.1.7 on 2021-03-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0020_auto_20210312_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-date_created',)},
        ),
    ]
