# Generated by Django 3.1.7 on 2021-05-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0021_auto_20210315_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagelog',
            options={'ordering': ['-date', '-id']},
        ),
    ]
