# Generated by Django 3.1.7 on 2021-06-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0022_auto_20210513_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_unsubscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='twilio_status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Autoreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('reply', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.organization')),
                ('prev_msg', models.ManyToManyField(blank=True, to='messenger.Message')),
                ('tags', models.ManyToManyField(blank=True, to='messenger.Tag')),
            ],
        ),
    ]
