# Generated by Django 3.2.5 on 2021-09-27 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0024_auto_20210707_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoreply',
            options={'verbose_name_plural': 'autoreplies'},
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.message'),
        ),
    ]
