# Generated by Django 3.2.5 on 2021-09-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0025_auto_20210927_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
