# Generated by Django 4.2.7 on 2023-11-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0028_auto_20230223_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='has_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='has_name',
            field=models.BooleanField(default=False),
        ),
    ]
