# Generated by Django 4.2.5 on 2024-06-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0029_contact_has_email_contact_has_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagelog',
            options={'ordering': ['-timestamp', '-id']},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RenameField(
            model_name='messagelog',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='date_received',
            new_name='timestamp',
        ),
    ]
