# Generated by Django 4.2.17 on 2025-01-17 01:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0031_tag_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('raw_cost', models.IntegerField(default=0)),
                ('adjusted_cost', models.IntegerField(default=0)),
                ('outgoing_msgs', models.IntegerField(default=0)),
                ('incoming_msgs', models.IntegerField(default=0)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.organization')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
