# Generated by Django 4.2.5 on 2025-01-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0032_contact_date_added'),
        ('messenger', '0032_invoice'),
    ]

    operations = [
    ]
