# Generated by Django 4.2.5 on 2025-01-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0033_merge_0032_contact_date_added_0032_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organization',
            name='account_id',
            field=models.IntegerField(default=1),
        ),
    ]
